name: comfyui
services:
  comfy:
    cpu_shares: 90
    command: []
    container_name: ComfyUI
    deploy:
      resources:
        limits:
          memory: 20480M
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    image: registry.cn-hangzhou.aliyuncs.com/openrepo/comfyui:latest
    labels:
      icon: https://github.com/justserdar/ZimaOS-AppStore/blob/main/Apps/comfyui/logo.png?raw=true
    ports:
      - target: 8188
        published: "8188"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/ComfyUI/models/checkpoints
        target: /ComfyUI/models/checkpoints
      - type: bind
        source: /DATA/AppData/ComfyUI/output
        target: /ComfyUI/output
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
    # CasaOS specific configuration for volume and port descriptions
    x-casaos:
      volumes:
        - container: /ComfyUI/models/checkpoints
          description:
            en_us: Container path for checkpoints /ComfyUI/models/checkpoints
        - container: /ComfyUI/output
          description:
            en_us: Container path for projects/rendered output /ComfyUI/output
x-casaos:
  developer: comfyanonymous
  author: JustSerdar
  category: Generative AI
  hostname: ""
  icon: https://github.com/justserdar/ZimaOS-AppStore/blob/main/Apps/comfyui/logo.png?raw=true
  index: /
  is_uncontrolled: false
  port_map: "8188"
  scheme: http
  store_app_id: comfyui
  title:
    custom: ComfyUI
    en_us: ComfyUI
