version: "3.7"
name: comfyui
services:
  comfyui:
    container_name: comfyui
    image: yanwk/comfyui-boot:cu126-slim
    ports:
      - "8189:8188"
    labels:
      - "casaos.port=8189"
      - "casaos.protocol=http"
      - "casaos.entrypoint=/"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8189"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 20480M
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    volumes:
      - /DATA/AppData/ComfyUI/models/checkpoints:/ComfyUI/models/checkpoints
      - /DATA/AppData/ComfyUI/custom_nodes:/ComfyUI/custom_nodes
      - /DATA/AppData/ComfyUI/input:/ComfyUI/input
      - /DATA/AppData/ComfyUI/output:/ComfyUI/output
      - /DATA/AppData/ComfyUI/user:/ComfyUI/user
      - /DATA/AppData/ComfyUI/script_examples:/ComfyUI/script_examples
      - /DATA/AppData/ComfyUI/comfy_extras:/ComfyUI/comfy_extras
    network_mode: bridge
    restart: unless-stopped
    # CasaOS specific configuration for volume and port descriptions
    x-casaos:
      volumes:
        - container: /ComfyUI/models/checkpoints
          description:
            en_us: Container path for checkpoints
        - container: /ComfyUI/custom_nodes
          description:
            en_us: Container path for custom nodes
        - container: /ComfyUI/input
          description:
            en_us: Container path for input files
        - container: /ComfyUI/output
          description:
            en_us: Container path for output files
        - container: /ComfyUI/user
          description:
            en_us: Container path for user settings
        - container: /ComfyUI/script_examples
          description:
            en_us: Container path for script examples
        - container: /ComfyUI/comfy_extras
          description:
            en_us: Container path for comfy extras

# CasaOS specific application metadata and configurations
x-casaos:
  architectures:
    - amd64
    - arm64
  main: comfyui
  description:
    en_us: ComfyUI is a powerful and modular stable diffusion GUI and backend with a strong focus on extensibility and performance.
  tagline:
    en_us: A powerful and modular stable diffusion GUI
  developer: comfyanonymous
  author: JustSerdar
  icon: https://raw.githubusercontent.com/justserdar/ZimaOS-AppStore/main/Apps/comfyui/logo.png
  thumbnail: https://raw.githubusercontent.com/justserdar/ZimaOS-AppStore/main/Apps/comfyui/logo.png
  title:
    en_us: ComfyUI
  category: Generative AI
  port_map: "8189"
  scheme: http
  index: /
  tips:
    before_install:
      en_us: |
        Visit: https://hub.docker.com/r/yanwk/comfyui-boot for the latest versions.