name: invokeai
services:
  invokeai:
    cpu_shares: 90
    command: []
    container_name: InvokeAI
    deploy:
      resources:
        limits:
          memory: 48000M
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    image: ghcr.io/invoke-ai/invokeai:latest
    labels:
      icon: https://github.com/justserdar/ZimaOS-AppStore/blob/main/Apps/invoke/logo.png?raw=true
    ports:
      - target: 9090
        published: "9090"
        protocol: tcp
    restart: unless-stopped
    volumes:       
    - /DATA/AppData/invokeai:/root/.invokeai
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
    # CasaOS specific configuration for volume and port descriptions
    x-casaos:
      volumes:
        - container: /root/.invokeai
          description:
            en_us: Container path for InvokeAI /root/.invokeai
x-casaos:
  author: JustSerdar
  category: Generative AI
  hostname: ""
  icon: https://github.com/justserdar/ZimaOS-AppStore/blob/main/Apps/invoke/logo.png?raw=true
  index: /
  is_uncontrolled: false
  port_map: "9090"
  scheme: http
  store_app_id: invoke
  title:
    custom: Invoke
    en_us: invoke

