name: invokeai
services:
  invokeai:
    cpu_shares: 90
    command: []
    container_name: InvokeAI
    deploy:
      resources:
        limits:
          memory: 48000M
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: -1
    image: ghcr.io/invoke-ai/invokeai:latest
    labels:
      icon: https://avatars.githubusercontent.com/u/113954515?s=48&v=4
    ports:
      - target: 9090
        published: "9090"
        protocol: tcp
    restart: unless-stopped
    volumes:       
    - /DATA/AppData/invokeai:/root/.invokeai
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: JustSerdar
  category: Generative AI
  hostname: ""
  icon: https://avatars.githubusercontent.com/u/113954515?s=48&v=4
  index: /
  is_uncontrolled: false
  port_map: "9090"
  scheme: http
  store_app_id: invokeai
  title:
    custom: InvokeAI
    en_us: invokeai

