version: "3.7"
services:
  cncjs:
    container_name: CNCjs
    image: cncjs/cncjs:latest
    ports:
      - "8005:8000"
    volumes:
      - /DATA/AppData/CNCjs:/cncjs
    network_mode: bridge
    hostname: cncjs
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
# CasaOS specific application metadata and configurations
x-casaos:
  architectures:
    - amd64
    - arm64
  main: CNCjs
  description:
    en_us: CNCjs is a self-hosted web application that allows you to manage your servers, applications, and services. It provides a simple and intuitive interface for managing your infrastructure, making it easy to deploy and manage your applications. With Coolify, you can easily manage your servers, applications, and services, providing a streamlined experience for managing your infrastructure.
  tagline:
    en_us: CNCjs
  developer: "cncjs" # Developer of coolify
  author: "JustSerdar" # Author of the docker compose
  icon: "https://github.com/cncjs/cncjs/blob/master/src/app/images/logo-square-256x256.png?raw=true"
  thumbnail: ""
  title:
    en_us: CNCjs
  category: Maker
  port_map: "8000"
  # Tips
  tips:
    before_install:
      en_us: |
        Read this before installing: https://community.bigbeartechworld.com/t/added-coolify-to-casaos/2186?u=dragonfire1119